name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout code to GitHub runner

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run tests with pytest (maxfail=1 to stop after the first failure)